### ISSUE TITLE
fail to set option into stc12c5a

### ISSUE THREAD

**Issue by trlsmax** [laborer/stcflash#11]
I have these error:
```
Programming: #################### done
Setting options...Traceback (most recent call last):
  File "/home/max/tools/stcflash", line 700, in <module>
    main()
  File "/home/max/tools/stcflash", line 696, in main
    program(Programmer(conn, opts.protocol), code, opts.erase_eeprom)
  File "/home/max/tools/stcflash", line 558, in program
    if prog.options(erase_eeprom=erase_eeprom):
  File "/home/max/tools/stcflash", line 457, in options
    self.send(0x8D, dat)
  File "/home/max/tools/stcflash", line 226, in send
    chksum = sum(buf[2:])
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by laborer** [comment]
This was an error that occurs only on Python2.  Now stcflash should set options fine on both Python2 and 3.

**Comment by trlsmax** [comment]
It work now. Thanks

**Comment by XioaoLing** [comment]
I have these error:

Detecting target...Traceback (most recent call last):
  File "stcflash.py", line 701, in <module>
    main()
  File "stcflash.py", line 697, in main
    program(Programmer(conn, opts.protocol), code, opts.erase_eeprom)
  File "stcflash.py", line 509, in program
    prog.detect()
  File "stcflash.py", line 243, in detect
    raise IOError()
IOError
