### ISSUE TITLE
STC15L2K60S2

### ISSUE THREAD

**Issue by blindman2k** [laborer/stcflash#4]
I have been trying to use stcflash to program the STC12C5A60S2's I have here and they appear to be ever so slightly incompatible. Do you have any ideas on how to adjust stcflash to work with this mcu?

```
$ python2.7 stcflash.py --port /dev/tty.usbserial-A703BXNC --protocol 12 --lowbaud 115200 --aispbaud 115200 --verbose program.bin
Connect to /dev/tty.usbserial-A703BXNC at baudrate 115200
Detecting target...INFO: [5045] Model ID: F4 88
INFO: [5046] Model name: Unknown F4 88
INFO: [5046] ROM size: None
INFO: [5046] Protocol ID: 12
INFO: [5046] Checksum mode: 2
INFO: [5046] UART Parity: EVEN
INFO: [5046] Info string [0]: 72 53 00 F4 88 01 06 70 A2 02 12 17 1B 1D 1F 00
INFO: [5046] Info string [1]: F4 F0 04 CF FF 7B 7F FF FF 14 09 04 60
 done
 FOSC: 5413.651MHz
 Model: Unknown F4 88 (ver7.2S)
Traceback (most recent call last):
  File "stcflash.py", line 582, in <module>
    main()
  File "stcflash.py", line 578, in main
    program(Programmer(conn, protocol), code)
  File "stcflash.py", line 438, in program
    cmd, dat = prog.recv()
  File "stcflash.py", line 185, in recv
    raise IOError()
IOError
```

And with debug logging turned on ...
```
$ python2.7 stcflash.py --port /dev/tty.usbserial-A703BXNC --protocol 12 --lowbaud 115200 --aispbaud 115200 --verbose --debug program.bin
Connect to /dev/tty.usbserial-A703BXNC at baudrate 115200
Detecting target...DEBUG: [10] send: 7F 7F
DEBUG: [62] recv:
DEBUG: [62] recv(..): timeout
DEBUG: [62] send: 7F 7F
DEBUG: [115] recv:
DEBUG: [115] recv(..): timeout
DEBUG: [115] send: 7F 7F
DEBUG: [167] recv:
DEBUG: [167] recv(..): timeout
DEBUG: [167] send: 7F 7F
DEBUG: [222] recv:
DEBUG: [222] recv(..): timeout
DEBUG: [222] send: 7F 7F
DEBUG: [275] recv:
DEBUG: [275] recv(..): timeout
DEBUG: [275] send: 7F 7F
...
DEBUG: [4381] recv(..): timeout
DEBUG: [4381] send: 7F 7F
DEBUG: [4385] recv: 46
DEBUG: [4385] recv: B9
DEBUG: [4385] recv: 68
DEBUG: [4385] recv: 00 34
DEBUG: [4401] recv: 50 68 63 83 A2 F7 BA 9F 01 50 9F 00 FD 00 D5 FF FF 72 53 00 F4 88 01 06 70 A2 02 12 17 1B 1D 1F 00 F4 F0 04 CF FF 7B 7F FF FF 14 09 04 60 14 F7 16
INFO: [4401] Model ID: F4 88
INFO: [4401] Model name: Unknown F4 88
INFO: [4401] ROM size: None
INFO: [4401] Protocol ID: 12
INFO: [4401] Checksum mode: 2
INFO: [4401] UART Parity: EVEN
INFO: [4402] Info string [0]: 72 53 00 F4 88 01 06 70 A2 02 12 17 1B 1D 1F 00
INFO: [4402] Info string [1]: F4 F0 04 CF FF 7B 7F FF FF 14 09 04 60
 done
 FOSC: 6225.837MHz
 Model: Unknown F4 88 (ver7.2S)
DEBUG: [4402] send: 46 B9 6A 00 0D 50 00 00 36 01 F4 88 02 7A 16
DEBUG: [4456] recv:
DEBUG: [4509] recv:
DEBUG: [4564] recv:
DEBUG: [4618] recv:
DEBUG: [4672] recv:
DEBUG: [4724] recv:
DEBUG: [4778] recv:
DEBUG: [4832] recv:
DEBUG: [4886] recv:
DEBUG: [4898] recv: 00 00 E6
DEBUG: [4898] recv: 9E 0C CF
DEBUG: [4968] recv: 00 00
DEBUG: [5022] recv:
DEBUG: [5074] recv:
DEBUG: [5128] recv:
DEBUG: [5181] recv:
DEBUG: [5234] recv:
DEBUG: [5289] recv:
DEBUG: [5344] recv:
DEBUG: [5399] recv:
DEBUG: [5454] recv:
DEBUG: [5454] recv(..): timeout
Traceback (most recent call last):
  File "stcflash.py", line 582, in <module>
    main()
  File "stcflash.py", line 578, in main
    program(Programmer(conn, protocol), code)
  File "stcflash.py", line 438, in program
    cmd, dat = prog.recv()
  File "stcflash.py", line 185, in recv
    raise IOError()
IOError
```

**Comment by laborer** [comment]
Could you run the program without parameter `--lowbaud 115200`?

**Comment by blindman2k** [comment]
It still times out, just without a response.

```
Connect to /dev/tty.usbserial-A703BXNC at baudrate 2400
Detecting target...DEBUG: [10] send: 7F 7F
DEBUG: [66] recv:
DEBUG: [66] recv(..): timeout
DEBUG: [66] send: 7F 7F
DEBUG: [117] recv:
DEBUG: [117] recv(..): timeout
DEBUG: [117] send: 7F 7F
DEBUG: [168] recv:
DEBUG: [168] recv(..): timeout
DEBUG: [168] send: 7F 7F
DEBUG: [223] recv:
DEBUG: [223] recv(..): timeout
DEBUG: [224] send: 7F 7F
DEBUG: [276] recv:
DEBUG: [276] recv(..): timeout
DEBUG: [276] send: 7F 7F
DEBUG: [331] recv:
DEBUG: [331] recv(..): timeout
DEBUG: [331] send: 7F 7F
DEBUG: [383] recv:
DEBUG: [383] recv(..): timeout
DEBUG: [384] send: 7F 7F
DEBUG: [436] recv:
DEBUG: [436] recv(..): timeout
DEBUG: [437] send: 7F 7F
DEBUG: [487] recv:
DEBUG: [488] recv(..): timeout
DEBUG: [488] send: 7F 7F
DEBUG: [540] recv:
DEBUG: [541] recv(..): timeout
DEBUG: [541] send: 7F 7F
DEBUG: [594] recv:
DEBUG: [594] recv(..): timeout
DEBUG: [595] send: 7F 7F
DEBUG: [649] recv:
DEBUG: [650] recv(..): timeout
DEBUG: [650] send: 7F 7F
DEBUG: [704] recv:
DEBUG: [704] recv(..): timeout
DEBUG: [704] send: 7F 7F
DEBUG: [715] recv: 46
DEBUG: [731] recv: B9
DEBUG: [731] recv(..): timeout
DEBUG: [731] send: 7F 7F
DEBUG: [731] recv: 68
DEBUG: [731] recv: 00 34
DEBUG: [954] recv: 50 68 63 83 A2 F7 BA 9F 01 50 9F 00 FD 27 1D FF FF 72 53 00 F4 88 01 06 70 A2 02 12 17 1B 1D 1F 00 F4 F0 04 CF FF 7B 7F FF FF 14 09 04 60 14 66 16
INFO: [955] Model ID: F4 88
INFO: [955] Model name: Unknown F4 88
INFO: [955] ROM size: None
INFO: [955] Protocol ID: 12
INFO: [955] Checksum mode: 2
INFO: [955] UART Parity: EVEN
INFO: [955] Info string [0]: 72 53 00 F4 88 01 06 70 A2 02 12 17 1B 1D 1F 00
INFO: [955] Info string [1]: F4 F0 04 CF FF 7B 7F FF FF 14 09 04 60
 done
 FOSC: 134.765MHz
 Model: Unknown F4 88 (ver7.2S)
DEBUG: [955] send: 46 B9 6A 00 0D 50 00 00 36 01 F4 88 02 7A 16
DEBUG: [1011] recv:
DEBUG: [1065] recv:
DEBUG: [1121] recv:
DEBUG: [1175] recv:
DEBUG: [1229] recv:
DEBUG: [1283] recv:
DEBUG: [1334] recv:
DEBUG: [1385] recv:
DEBUG: [1440] recv:
DEBUG: [1494] recv:
DEBUG: [1549] recv:
DEBUG: [1602] recv:
DEBUG: [1655] recv:
DEBUG: [1708] recv:
DEBUG: [1759] recv:
DEBUG: [1814] recv:
DEBUG: [1867] recv:
DEBUG: [1919] recv:
DEBUG: [1973] recv:
DEBUG: [1974] recv(..): timeout
Traceback (most recent call last):
  File "stcflash.py", line 582, in <module>
    main()
  File "stcflash.py", line 578, in main
    program(Programmer(conn, protocol), code)
  File "stcflash.py", line 438, in program
    cmd, dat = prog.recv()
  File "stcflash.py", line 185, in recv
    raise IOError()
IOError
```

I have a full debug trace of stc-isp for Windows running and it's flawless, both at 2400 and 115200.
https://www.dropbox.com/s/72hx4ptwfk1f39o/program%20short.log (ignore my comments and snips).

**Comment by laborer** [comment]
Thanks for the information.  Apparently, the packets received from serial port by stcflash are exactly the same as which received by the official stc-isp program in Windows.  This means the serial communication is fine under Linux.  However, the protocol looks different than the STC12C5A series MCUs I use.  Your STC12C5A60S2 must be a newer version using a slightly modified protocol that is not supported by stcflash/stcdude/etc yet.  You can run the official stc-isp program in Windows several times with different baudrate and oscillator settings, and post the captured serial communication here.  We might be able to reverse engineer the protocol and add support to it in the next version of stcflash.

**Comment by blindman2k** [comment]
I will do that tomorrow, as I don't have access to the windows machine today. I might also see if I can access an MCU with an older boot loader.

**Comment by blindman2k** [comment]
Attached are five logs of various baud rates and Input IRC frequencies.
Happy to capture more if you need.

**Comment by laborer** [comment]
The protocol looks very similar to STC15 series MCUs rather than STC12 series.

Wait...  It is...
```
  MCU type: STC15L2K60S2
  F/W version: 7.2.1S
```

Sorry, stcflash doesn't support STC15 series yet.  I will work on it.

**Comment by blindman2k** [comment]
That might explain a bit :)
I was told what I was told.

**Comment by blindman2k** [comment]
Is there anything I can do to assist? I have some deadlines looming :(
